import type { PortfolioLanguage } from '../../data/portfolioCapabilities';

export const datePresentationCopy = {
  en: {
    eyebrow: 'UTILITY / 01',
    title: 'A date should inform, not interrupt.',
    intro: 'Try a strict calendar-date presenter that keeps malformed values local and the rest of the interface usable.',
    inputLabel: 'ISO calendar date',
    inputHint: 'Use YYYY-MM-DD. Timestamps and ambiguous regional formats are intentionally rejected.',
    outputLabel: 'Presented value',
    valid: 'Valid calendar date',
    empty: 'Waiting for a date',
    invalid: 'Invalid input contained',
    fallback: 'Date unavailable',
    presetsLabel: 'Test cases',
    presets: [
      { label: 'Known date', value: '2026-09-13' },
      { label: 'Leap day', value: '2024-02-29' },
      { label: 'Broken date', value: '2023-02-29' },
      { label: 'Empty', value: '' },
    ],
    contractTitle: 'Contract',
    apiLabel: 'API contract',
    contract: ['Strict YYYY-MM-DD input', 'UTC-stable calendar output', 'No network or storage'],
    limitsTitle: 'Deliberate limits',
    limits: 'No timestamps, relative dates, durations, or timezone conversion.',
    source: 'Read the public engineering note',
  },
  he: {
    eyebrow: 'כלי / 01',
    title: 'תאריך צריך ליידע, לא לקטוע.',
    intro: 'נסו מציג תאריך קשיח שמגביל ערך פגום לשדה המקומי ומשאיר את שאר הממשק שמיש.',
    inputLabel: 'תאריך קלנדרי בתקן ISO',
    inputHint: 'השתמשו ב־YYYY-MM-DD. חותמות זמן ופורמטים אזוריים דו־משמעיים נדחים במכוון.',
    outputLabel: 'הערך המוצג',
    valid: 'תאריך קלנדרי תקין',
    empty: 'ממתין לתאריך',
    invalid: 'הקלט הפגום נותר מקומי',
    fallback: 'התאריך אינו זמין',
    presetsLabel: 'מקרי בדיקה',
    presets: [
      { label: 'תאריך ידוע', value: '2026-09-13' },
      { label: 'יום מעובר', value: '2024-02-29' },
      { label: 'תאריך שבור', value: '2023-02-29' },
      { label: 'ריק', value: '' },
    ],
    contractTitle: 'חוזה',
    apiLabel: 'חוזה API',
    contract: ['קלט קשיח YYYY-MM-DD', 'פלט קלנדרי יציב ב־UTC', 'ללא רשת או אחסון'],
    limitsTitle: 'מגבלות מכוונות',
    limits: 'ללא חותמות זמן, תאריכים יחסיים, משכי זמן או המרת אזור זמן.',
    source: 'לקריאת הרשומה ההנדסית הפומבית',
  },
} as const satisfies Record<PortfolioLanguage, object>;
