import type { BlogLanguage, BlogPostMeta } from './types';

/**
 * Canonical lightweight metadata for every localized post. Keep post copy here;
 * posts.ts only binds each record to its MDX component so metadata consumers do
 * not pull the article bodies into their bundle.
 */
const metadata = {
  'operating-system-under-apps:he': {
      slug: 'operating-system-under-apps',
      language: 'he',
      title: 'מהי מערכת הפעלה?',
      excerpt: 'מדריך מעשי למה שקורה מתחת לאפליקציות: kernel, system calls, processes, threads, scheduler, זיכרון וירטואלי, file descriptors, page cache והרצת Process ב-Java.',
      date: '2026-07-14',
      readTime: '14 דקות קריאה',
      tags: ['Operating Systems', 'Java', 'Systems'],
      featured: false,
    },
  'operating-system-under-apps:en': {
      slug: 'operating-system-under-apps',
      language: 'en',
      title: 'What is an operating system?',
      excerpt: 'A practical guide to what happens under applications: kernels, system calls, processes, threads, scheduling, virtual memory, file descriptors, page cache, and Java ProcessBuilder.',
      date: '2026-07-14',
      readTime: '14 min read',
      tags: ['Operating Systems', 'Java', 'Systems'],
      featured: false,
    },
  'hardware-input-output-devices:he': {
      slug: 'hardware-input-output-devices',
      language: 'he',
      title: 'מה באמת קורה כשלוחצים על מקש?',
      excerpt: 'מדריך מעשי לקלט, פלט והתקני חומרה: מקלדות, drivers, interrupts, buffers, backpressure, DMA, latency, flush, ADC וקריאות חלקיות.',
      date: '2026-07-13',
      readTime: '12 דקות קריאה',
      tags: ['Hardware', 'I/O', 'Systems'],
      featured: false,
    },
  'hardware-input-output-devices:en': {
      slug: 'hardware-input-output-devices',
      language: 'en',
      title: 'What really happens when you press a key?',
      excerpt: 'A practical guide to input, output, and hardware devices: keyboards, drivers, interrupts, buffers, backpressure, DMA, latency, flush, ADC, and partial reads.',
      date: '2026-07-13',
      readTime: '12 min read',
      tags: ['Hardware', 'I/O', 'Systems'],
      featured: false,
    },
  'java-unicode-string-length:he': {
      slug: 'java-unicode-string-length',
      language: 'he',
      title: 'למה String.length() לא באמת סופר תווים',
      excerpt: 'מדריך מעשי ל-Unicode ב-Java: יחידות UTF-16, נקודות קוד, בתי UTF-8, grapheme clusters, normalization וחיתוך טקסט בלי לשבור אימוג׳י.',
      date: '2026-07-13',
      readTime: '13 דקות קריאה',
      tags: ['Java', 'Unicode', 'Text'],
      featured: false,
    },
  'java-unicode-string-length:en': {
      slug: 'java-unicode-string-length',
      language: 'en',
      title: 'Why String.length() does not really count characters',
      excerpt: 'A practical guide to Unicode in Java: UTF-16 code units, code points, UTF-8 bytes, grapheme clusters, normalization, and truncating text without breaking emoji.',
      date: '2026-07-13',
      readTime: '13 min read',
      tags: ['Java', 'Unicode', 'Text'],
      featured: false,
    },
  'binary-bitwise-java:he': {
      slug: 'binary-bitwise-java',
      language: 'he',
      title: 'איך מספרים חיים בתוך המחשב',
      excerpt: 'מדריך מעשי לבינארי, המרות, הזזות ביטים, מסכות הרשאות, overflow וההבדל בין >> ל->>> ב-Java.',
      date: '2026-07-12',
      readTime: '12 דקות קריאה',
      tags: ['Binary', 'Java', 'Computer Science'],
      featured: false,
    },
  'binary-bitwise-java:en': {
      slug: 'binary-bitwise-java',
      language: 'en',
      title: 'How numbers live inside a computer',
      excerpt: 'A practical guide to binary, conversions, bit shifts, permission masks, overflow, and the difference between >> and >>> in Java.',
      date: '2026-07-12',
      readTime: '12 min read',
      tags: ['Binary', 'Java', 'Computer Science'],
      featured: false,
    },
  'performance-optimizations-need-product-verification:he': {
      slug: 'performance-optimizations-need-product-verification',
      language: 'he',
      title: 'כשאופטימיזציית ביצועים מסתירה תוכן',
      excerpt: 'איך content-visibility ו-reveal-on-scroll באתר עסקי הובילו לתיקון שמזכיר: ביצועים טובים חייבים להיבדק מול חוויית המשתמש בפועל.',
      date: '2026-07-12',
      readTime: '6 דקות קריאה',
      tags: ['Performance', 'Frontend', 'UX'],
      featured: false,
    },
  'performance-optimizations-need-product-verification:en': {
      slug: 'performance-optimizations-need-product-verification',
      language: 'en',
      title: 'When a performance optimization hides content',
      excerpt: 'How content-visibility and reveal-on-scroll on a business site led to a fix that reinforced a simple rule: performance must be verified against the real user experience.',
      date: '2026-07-12',
      readTime: '6 min read',
      tags: ['Performance', 'Frontend', 'UX'],
      featured: false,
    },
  'what-is-inside-a-file:he': {
      slug: 'what-is-inside-a-file',
      language: 'he',
      title: 'מה באמת יש בתוך קובץ?',
      excerpt: 'הסבר מעשי על ביטים, בתים, UTF-8, תמונות, signed ו-unsigned, overflow, byte ב-Java, גודל בדיסק וסדר בתים.',
      date: '2026-07-12',
      readTime: '10 דקות קריאה',
      tags: ['Data', 'Files', 'Java'],
      featured: false,
    },
  'what-is-inside-a-file:en': {
      slug: 'what-is-inside-a-file',
      language: 'en',
      title: 'What is really inside a file?',
      excerpt: 'A practical explanation of bits, bytes, UTF-8, images, signed and unsigned numbers, overflow, Java bytes, size on disk, and byte order.',
      date: '2026-07-12',
      readTime: '10 min read',
      tags: ['Data', 'Files', 'Java'],
      featured: false,
    },
  'ram-vs-storage:he': {
      slug: 'ram-vs-storage',
      language: 'he',
      title: 'RAM לעומת אחסון',
      excerpt: 'למה SSD פנוי לא מונע מהמחשב להיתקע, איך RAM, Working Set, Swap, RSS ו-Memory Pressure משפיעים על עבודה עם Android Studio, אמולטור ודפדפן.',
      date: '2026-07-12',
      readTime: '10 דקות קריאה',
      tags: ['Memory', 'Performance', 'macOS'],
      featured: false,
    },
  'ram-vs-storage:en': {
      slug: 'ram-vs-storage',
      language: 'en',
      title: 'RAM versus storage',
      excerpt: 'Why free SSD space does not stop a computer from freezing, and how RAM, working set, swap, RSS, and memory pressure affect real development work.',
      date: '2026-07-12',
      readTime: '10 min read',
      tags: ['Memory', 'Performance', 'macOS'],
      featured: false,
    },
  'what-the-cpu-really-does:he': {
      slug: 'what-the-cpu-really-does',
      language: 'he',
      title: 'מה המעבד באמת עושה',
      excerpt: 'הסבר מעשי על Fetch, Decode, Execute, אוגרים, Cache, Pipeline, IPC, ליבות, GHz ולמה לולאת Python אחת לא משתמשת אוטומטית בכל המעבדים.',
      date: '2026-07-11',
      readTime: '10 דקות קריאה',
      tags: ['CPU', 'Performance', 'Python'],
      featured: false,
    },
  'what-the-cpu-really-does:en': {
      slug: 'what-the-cpu-really-does',
      language: 'en',
      title: 'What the CPU really does',
      excerpt: 'A practical explanation of Fetch, Decode, Execute, registers, cache, pipelines, IPC, cores, GHz, and why one Python loop does not automatically use every CPU.',
      date: '2026-07-11',
      readTime: '10 min read',
      tags: ['CPU', 'Performance', 'Python'],
      featured: false,
    },
  'spa-routes-need-real-http:he': {
      slug: 'spa-routes-need-real-http',
      language: 'he',
      title: 'גם SPA צריך URL אמיתי',
      excerpt: 'על תיקון נתיבי בלוג ו-case studies בפורטפוליו כך שיחזירו HTTP 200, metadata נכון ו-sitemap, ולא רק ירונדרו אחרי טעינת React.',
      date: '2026-07-05',
      readTime: '6 דקות קריאה',
      tags: ['Frontend', 'SEO', 'Production'],
      featured: false,
    },
  'spa-routes-need-real-http:en': {
      slug: 'spa-routes-need-real-http',
      language: 'en',
      title: 'Even an SPA needs real URLs',
      excerpt: 'About fixing portfolio blog and case study routes so they return HTTP 200, correct metadata, and sitemap coverage, not only client-side rendering after React loads.',
      date: '2026-07-05',
      readTime: '6 min read',
      tags: ['Frontend', 'SEO', 'Production'],
      featured: false,
    },
  'seo-discovery-is-product-work:he': {
      slug: 'seo-discovery-is-product-work',
      language: 'he',
      title: 'SEO הוא לא קישוט, הוא שכבת גילוי במוצר',
      excerpt: 'על העבודה ב-Online Converter שהפכה דפי קטגוריה, קישורים פנימיים ו-snippets ממטלת SEO לשכבת discovery שנבדקת כמו קוד.',
      date: '2026-06-28',
      readTime: '6 דקות קריאה',
      tags: ['SEO', 'Product', 'Discovery'],
      featured: false,
    },
  'seo-discovery-is-product-work:en': {
      slug: 'seo-discovery-is-product-work',
      language: 'en',
      title: 'SEO is not decoration, it is product discovery',
      excerpt: 'About turning category pages, internal links, and snippets in Online Converter from an SEO checklist into a tested discovery layer.',
      date: '2026-06-28',
      readTime: '6 min read',
      tags: ['SEO', 'Product', 'Discovery'],
      featured: false,
    },
  'privacy-safe-product-analytics:he': {
      slug: 'privacy-safe-product-analytics',
      language: 'he',
      title: 'איך מודדים מוצר בלי לקרוא את הדאטה של המשתמש',
      excerpt: 'על הוספת אנליטיקה ל-Online Converter בצורה שמודדת פעולות, לא תוכן רגיש, ושומרת על ההבטחה של כלי שרץ בצד לקוח.',
      date: '2026-06-24',
      readTime: '5 דקות קריאה',
      tags: ['Analytics', 'Privacy', 'Product'],
      featured: false,
    },
  'privacy-safe-product-analytics:en': {
      slug: 'privacy-safe-product-analytics',
      language: 'en',
      title: 'Measuring product usage without reading user data',
      excerpt: 'About adding analytics to Online Converter in a way that measures actions, not sensitive content, and preserves the client-side privacy promise.',
      date: '2026-06-24',
      readTime: '5 min read',
      tags: ['Analytics', 'Privacy', 'Product'],
      featured: false,
    },
  'google-translate-name-bug:he': {
      slug: 'google-translate-name-bug',
      language: 'he',
      title: 'כשגוגל תרגם את השם שלי לג׳יבריש',
      excerpt: 'איך תרגום אוטומטי שיבש את השם שלי בפורטפוליו, ולמה שמות, לוגואים וזהות מותג צריכים גבולות ברורים ב-DOM.',
      date: '2026-06-24',
      readTime: '5 דקות קריאה',
      tags: ['Frontend', 'i18n', 'UX'],
      featured: false,
    },
  'google-translate-name-bug:en': {
      slug: 'google-translate-name-bug',
      language: 'en',
      title: 'When Google translated my name into gibberish',
      excerpt: 'How automatic translation corrupted my portfolio name, and why names, logos, and brand identity need clear boundaries in the DOM.',
      date: '2026-06-24',
      readTime: '5 min read',
      tags: ['Frontend', 'i18n', 'UX'],
      featured: false,
    },
  'small-project-architecture:he': {
      slug: 'small-project-architecture',
      language: 'he',
      title: 'גם פרויקט קטן צריך גבולות ברורים',
      excerpt: 'למה אתר קטן או פורטפוליו צריכים מבנה קוד שמאפשר לחזור, לעדכן ולהמשיך לעבוד בלי לפחד לשבור אמון.',
      date: '2026-06-21',
      readTime: '5 דקות קריאה',
      tags: ['Architecture', 'Frontend', 'Product'],
      featured: false,
    },
  'small-project-architecture:en': {
      slug: 'small-project-architecture',
      language: 'en',
      title: 'Even small projects need clear boundaries',
      excerpt: 'Why a small website or portfolio still needs code structure that makes it easy to return, update, and keep working without breaking trust.',
      date: '2026-06-21',
      readTime: '5 min read',
      tags: ['Architecture', 'Frontend', 'Product'],
      featured: false,
    },
  'deployment-is-product:he': {
      slug: 'deployment-is-product',
      language: 'he',
      title: 'למה פריסה היא חלק מהמוצר',
      excerpt: 'על ההבדל בין “עובד אצלי” לבין מוצר קטן שאפשר לסמוך עליו, ולמה build, דומיין ובדיקות הם חלק מחוויית המשתמש.',
      date: '2026-06-19',
      readTime: '5 דקות קריאה',
      tags: ['Deployment', 'Product', 'Credibility'],
      featured: false,
    },
  'deployment-is-product:en': {
      slug: 'deployment-is-product',
      language: 'en',
      title: 'Why deployment is part of the product',
      excerpt: 'About the gap between “works on my machine” and a small product people can trust, and why builds, domains, and tests shape the user experience.',
      date: '2026-06-19',
      readTime: '5 min read',
      tags: ['Deployment', 'Product', 'Credibility'],
      featured: false,
    },
  'catering-whatsapp:he': {
      slug: 'catering-whatsapp',
      language: 'he',
      title: 'איך בניתי אתר עסקי שמוביל ל-WhatsApp',
      excerpt: 'על הפיתוי להפוך אתר קטן למערכת גדולה, ולמה לפעמים ההחלטה הכי חכמה היא להוביל לשיחת WhatsApp אחת טובה.',
      date: '2026-06-18',
      readTime: '6 דקות קריאה',
      tags: ['Case Study', 'Frontend', 'WhatsApp'],
      featured: true,
    },
  'catering-whatsapp:en': {
      slug: 'catering-whatsapp',
      language: 'en',
      title: 'How I built a business site around WhatsApp',
      excerpt: 'About the temptation to turn a small website into a large system, and why the smarter product decision was one strong WhatsApp conversation.',
      date: '2026-06-18',
      readTime: '6 min read',
      tags: ['Case Study', 'Frontend', 'WhatsApp'],
      featured: true,
    },
  'credible-portfolio:he': {
      slug: 'credible-portfolio',
      language: 'he',
      title: 'מה למדתי מבניית פורטפוליו אמין',
      excerpt: 'למה סטאק טכנולוגי הוא לא סיפור, איך הופכים פרויקטים לקייסים קצרים, ומה גורם לפורטפוליו להרגיש באמת ניתן לבדיקה.',
      date: '2026-06-18',
      readTime: '6 דקות קריאה',
      tags: ['Portfolio', 'Product', 'Credibility'],
      featured: false,
    },
  'credible-portfolio:en': {
      slug: 'credible-portfolio',
      language: 'en',
      title: 'What I learned from building a credible portfolio',
      excerpt: 'Why a technology stack is not a story, how projects become short case studies, and what makes a portfolio feel genuinely verifiable.',
      date: '2026-06-18',
      readTime: '6 min read',
      tags: ['Portfolio', 'Product', 'Credibility'],
      featured: false,
    },
} as const satisfies Record<string, BlogPostMeta>;

export const blogPostMetadata = Object.values(metadata);

export const getLatestBlogPostMetadata = (language: BlogLanguage, limit = 3) =>
  blogPostMetadata
    .filter((post) => post.language === language)
    .sort((a, b) => Date.parse(b.date) - Date.parse(a.date))
    .slice(0, Math.max(0, limit));

export const getBlogPostMetadata = (slug: string, language: BlogLanguage) =>
  metadata[`${slug}:${language}` as keyof typeof metadata];

export const blogPostMetadataByKey = metadata;
